### ISSUE TITLE
Submit request

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/bartender#2]
Method is `POST` and url is `/api/job/{appname}` (appname could be haddock3)

With header: `Authorization: <some token>`

Body of request is a multipart form with single file which is an archive with config file and data files.

**Comment by sverhoeven** [comment]
```yaml
appname
  haddock3:
    cfg: workflow.cfg
    cmd: haddock3  workflow.cfg
```
