### ISSUE TITLE
Application without config

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/bartender#42]
An application could not need a config file. We should support this.

For example haddock3-pp can run on all the PDB files the user submtted using following config.yaml

```yaml
applications:
  haddock3-pp:
    label: HADDOCK3 preprocess PDB files
    command: haddock3-pp --output-directory . *.pdb
```

**Comment by sverhoeven** [comment]
Since #81 following is allowed

```yaml
applications:
  du:
    command_template: du -hs .
```
